#ifndef SLASH_LOG_HH
#define SLASH_LOG_HH

#include "soil/Log.hh"

#define SLASH_LOG_INIT(x) SOIL_LOG_INIT(x)

#define SLASH_TRACE SOIL_TRACE
#define SLASH_DEBUG SOIL_DEBUG
#define SLASH_INFO  SOIL_INFO
#define SLASH_WARNING SOIL_WARNING
#define SLASH_ERROR SOIL_ERROR
#define SLASH_FATAL SOIL_FATAL
#define SLASH_PDU SOIL_PDU
#define SLASH_CUSTOM SOIL_CUSTOM


#endif

